// Package learningscope owns the persisted contracts that separate one
// system-learning topic from its siblings.
package learningscope

import (
	"encoding/json"
	"errors"
	"os"
	"regexp"
	"strings"
	"time"
)

const SchemaVersion = 1

const (
	StatusDraft = "draft"
	StatusReady = "ready"

	SourceStandalone    = "standalone"
	SourceDisciplineMap = "discipline-map"
)

var topicIDPattern = regexp.MustCompile(`^[a-z0-9]+(?:-[a-z0-9]+)*$`)

// Source records where a learning scope came from. Map-origin projects keep a
// copied snapshot, so regenerating the map does not silently mutate them.
type Source struct {
	Type    string `json:"type"`
	MapSlug string `json:"mapSlug,omitempty"`
	TopicID string `json:"topicId,omitempty"`
}

// Topic is the canonical boundary of one actionable topic generated by the
// encyclopedia Agent.
type Topic struct {
	ID              string   `json:"id"`
	Title           string   `json:"title"`
	ChapterTitle    string   `json:"chapterTitle"`
	Goal            string   `json:"goal"`
	TeachingOutline string   `json:"teachingOutline,omitempty"`
	InScope         []string `json:"inScope"`
	OutOfScope      []string `json:"outOfScope"`
	Prerequisites   []string `json:"prerequisites"`
	OwnedConcepts   []string `json:"ownedConcepts"`
	ReusedConcepts  []string `json:"reusedConcepts"`
}

// Catalog is written next to overview.md by the encyclopedia Agent.
type Catalog struct {
	SchemaVersion int     `json:"schemaVersion"`
	Topics        []Topic `json:"topics"`
	UpdatedAt     string  `json:"updatedAt"`
}

// Scope is copied into every system-learning project as learning-scope.json.
type Scope struct {
	SchemaVersion   int      `json:"schemaVersion"`
	Status          string   `json:"status"`
	Title           string   `json:"title"`
	ChapterTitle    string   `json:"chapterTitle,omitempty"`
	Goal            string   `json:"goal"`
	TeachingOutline string   `json:"teachingOutline,omitempty"`
	InScope         []string `json:"inScope"`
	OutOfScope      []string `json:"outOfScope"`
	Prerequisites   []string `json:"prerequisites"`
	OwnedConcepts   []string `json:"ownedConcepts"`
	ReusedConcepts  []string `json:"reusedConcepts"`
	Source          Source   `json:"source"`
	UpdatedAt       string   `json:"updatedAt"`
}

// NewDraft creates the common starting point for a standalone system-learning
// project. Intro may finalize this file after learner calibration.
func NewDraft(title string, now time.Time) Scope {
	return Scope{
		SchemaVersion:  SchemaVersion,
		Status:         StatusDraft,
		Title:          strings.TrimSpace(title),
		Goal:           "",
		InScope:        []string{},
		OutOfScope:     []string{},
		Prerequisites:  []string{},
		OwnedConcepts:  []string{},
		ReusedConcepts: []string{},
		Source:         Source{Type: SourceStandalone},
		UpdatedAt:      now.UTC().Format(time.RFC3339),
	}
}

// SnapshotFromTopic creates an immutable-at-creation map scope snapshot.
func SnapshotFromTopic(mapSlug string, topic Topic, now time.Time) Scope {
	normalizeTopic(&topic)
	return Scope{
		SchemaVersion:   SchemaVersion,
		Status:          StatusReady,
		Title:           topic.Title,
		ChapterTitle:    topic.ChapterTitle,
		Goal:            topic.Goal,
		TeachingOutline: topic.TeachingOutline,
		InScope:         clone(topic.InScope),
		OutOfScope:      clone(topic.OutOfScope),
		Prerequisites:   clone(topic.Prerequisites),
		OwnedConcepts:   clone(topic.OwnedConcepts),
		ReusedConcepts:  clone(topic.ReusedConcepts),
		Source: Source{
			Type:    SourceDisciplineMap,
			MapSlug: strings.TrimSpace(mapSlug),
			TopicID: topic.ID,
		},
		UpdatedAt: now.UTC().Format(time.RFC3339),
	}
}

func ReadCatalog(path string) (Catalog, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return Catalog{}, err
	}
	var catalog Catalog
	if err := json.Unmarshal(data, &catalog); err != nil {
		return Catalog{}, err
	}
	if err := ValidateCatalog(&catalog); err != nil {
		return Catalog{}, err
	}
	return catalog, nil
}

func MarshalScope(scope Scope) ([]byte, error) {
	return json.MarshalIndent(scope, "", "  ")
}

func EmptyCatalog() Catalog {
	return Catalog{SchemaVersion: SchemaVersion, Topics: []Topic{}, UpdatedAt: ""}
}

func FindTopic(catalog Catalog, id string) (Topic, bool) {
	id = strings.TrimSpace(id)
	for _, topic := range catalog.Topics {
		if topic.ID == id {
			return topic, true
		}
	}
	return Topic{}, false
}

func ValidateCatalog(catalog *Catalog) error {
	if catalog.SchemaVersion != SchemaVersion {
		return errors.New("unsupported_discipline_topics_schema")
	}
	if len(catalog.Topics) > 500 {
		return errors.New("discipline_topics_too_large")
	}
	if catalog.Topics == nil {
		catalog.Topics = []Topic{}
	}
	seenIDs := map[string]bool{}
	seenTitles := map[string]bool{}
	ownedBy := map[string]string{}
	for i := range catalog.Topics {
		topic := &catalog.Topics[i]
		normalizeTopic(topic)
		if topic.ID == "" || len(topic.ID) > 120 || !topicIDPattern.MatchString(topic.ID) ||
			topic.Title == "" || len(topic.Title) > 180 ||
			topic.ChapterTitle == "" || len(topic.ChapterTitle) > 180 ||
			topic.Goal == "" || len(topic.Goal) > 600 ||
			len(topic.InScope) == 0 || len(topic.OwnedConcepts) == 0 {
			return errors.New("invalid_discipline_topic")
		}
		if seenIDs[topic.ID] || seenTitles[topic.Title] {
			return errors.New("duplicate_discipline_topic")
		}
		seenIDs[topic.ID] = true
		seenTitles[topic.Title] = true
		for _, concept := range topic.OwnedConcepts {
			key := strings.ToLower(concept)
			if owner, exists := ownedBy[key]; exists && owner != topic.ID {
				return errors.New("duplicate_owned_concept")
			}
			ownedBy[key] = topic.ID
		}
	}
	return nil
}

// ValidateAgainstOverview ensures the structured catalog is not a second,
// drifting topic list. New-contract actionable topics are exactly the H4
// headings, in the same order.
func ValidateAgainstOverview(catalog Catalog, markdown string) error {
	headings := make([]string, 0)
	for _, rawLine := range strings.Split(markdown, "\n") {
		line := strings.TrimSpace(strings.TrimSuffix(rawLine, "\r"))
		if !strings.HasPrefix(line, "#### ") || strings.HasPrefix(line, "##### ") {
			continue
		}
		title := strings.TrimSpace(strings.TrimLeft(strings.TrimSpace(strings.TrimPrefix(line, "#### ")), "*_`"))
		title = strings.TrimSpace(strings.TrimRight(title, "*_`"))
		headings = append(headings, title)
	}
	if len(headings) != len(catalog.Topics) {
		return errors.New("discipline_topics_overview_mismatch")
	}
	for i, title := range headings {
		if catalog.Topics[i].Title != title {
			return errors.New("discipline_topics_overview_mismatch")
		}
	}
	return nil
}

func normalizeTopic(topic *Topic) {
	topic.ID = strings.TrimSpace(topic.ID)
	topic.Title = strings.TrimSpace(topic.Title)
	topic.ChapterTitle = strings.TrimSpace(topic.ChapterTitle)
	topic.Goal = strings.TrimSpace(topic.Goal)
	topic.TeachingOutline = strings.TrimSpace(topic.TeachingOutline)
	topic.InScope = normalizeList(topic.InScope)
	topic.OutOfScope = normalizeList(topic.OutOfScope)
	topic.Prerequisites = normalizeList(topic.Prerequisites)
	topic.OwnedConcepts = normalizeList(topic.OwnedConcepts)
	topic.ReusedConcepts = normalizeList(topic.ReusedConcepts)
}

func normalizeList(values []string) []string {
	if values == nil {
		return []string{}
	}
	if len(values) > 100 {
		values = values[:100]
	}
	result := make([]string, 0, len(values))
	seen := map[string]bool{}
	for _, value := range values {
		value = strings.TrimSpace(value)
		if value == "" || len(value) > 300 || seen[value] {
			continue
		}
		seen[value] = true
		result = append(result, value)
	}
	return result
}

func clone(values []string) []string {
	return append([]string{}, values...)
}
